version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: App-projeto
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: librastils
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librastils
      SPRING_DATASOURCE_USERNAME: App-projeto
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  postgres_data:
